# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data-mountains',
                'doc_host': 'https://joel-lbth.github.io',
                'git_url': 'https://github.com/joel-lbth/data-mountains',
                'lib_path': 'data_mountains'},
  'syms': { 'data_mountains.core': {'data_mountains.core.foo': ('core.html#foo', 'data_mountains/core.py')},
            'data_mountains.mountainise': { 'data_mountains.mountainise.make_peak': ( 'mountainise.html#make_peak',
                                                                                      'data_mountains/mountainise.py'),
                                            'data_mountains.mountainise.plot': ('mountainise.html#plot', 'data_mountains/mountainise.py'),
                                            'data_mountains.mountainise.points_to_peaks': ( 'mountainise.html#points_to_peaks',
                                                                                            'data_mountains/mountainise.py'),
                                            'data_mountains.mountainise.project_data_to_spatial_range': ( 'mountainise.html#project_data_to_spatial_range',
                                                                                                          'data_mountains/mountainise.py')}}}
